### ISSUE TITLE
NoMoreRecipeConflict Repeat crashes

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/ATM-2#10]
Opened issue on their github here: https://github.com/GotoLink/RecipeHandler/issues/8

After logging out (or kicked) from a server, clients will [crash-to-desktop](https://pastebin.com/dRPHvGUc) when trying to log back in.

It's a very widespread/consistent issue for many users (if not everyone outright). If the mod dev can find/correct the issue it should be fine otherwise we should consider removing it from the pack and handling recipe conflicts manually (i.e. crafttweaker).

**Comment by whatthedrunk** [comment]
Removed for the next version. Now to wait and see all the duplicate recipes that exist :P.
