### ISSUE TITLE
Iron Duping Recipes

### ISSUE THREAD

**Issue by SirLyle** [AllTheMods/ATM-2#11]
Not sure this is a "bug" per se. But there are a few short sequences of steps to get infinite iron (given some power and lava) and one for gold using the same two machines.

Using the sequence Rolling Machine → Smeltery → Casting (in order of net gain): 
* 5 iron ingots → 2 Minecarts → 9 iron ingots
* 6 iron ingots → 24 iron bars → 9 iron ingots
* 6 iron ingots → 4 iron doors → 8 iron ingots
* 2 iron ingots → 2 weighted pressure plates → 4 iron ingots
* 5 iron ingots → 2 iron buckets → 6 iron ingots

For gold you can use the pressure plate sequence:
* 2 iron ingots → 2 weighted pressure plates → 4 iron ingots

Bonus sequence not using the rolling machine:
* *Craft* Tech Reborn's Iron Furnace using the 5 iron + Vanilla Furnace recipe
* Melt down for 8 iron ingots (you do lose 8 cobble stone)

**Comment by Boomflex** [comment]
Old issue.

Fixed in newer builds.
