### ISSUE TITLE
Cyclic Garden Scythe duplicating items.

### ISSUE THREAD

**Issue by NoVac101** [AllTheMods/ATM-2#12]
https://youtu.be/aXdki6c5Vdk

So far the Pergola from terraqueous is the only item I've tested on. I imagine its just the 2 mods interactions with each other.

**Comment by whatthedrunk** [comment]
Can confirm this happens, pretty weird lol.

**Comment by Boomflex** [comment]
Old issue.

Fixed in newer builds.
