### ISSUE TITLE
All the Mods 2 - Experience Solidifer Uncraftable

### ISSUE THREAD

**Issue by Vyraal1** [AllTheMods/ATM-2#13]
Solidified Experience is disabled as a mob drop in configs, with the default experience solidifier recipe this means it is uncraftable.

- Using latest version on the official server

**Comment by OrdinatorStouff** [comment]
Thanks we actually were aware of this recently and intend to fix it with some recipe changes

**Comment by whatthedrunk** [comment]
Next update v0.67 will add the experience drops again.
