### ISSUE TITLE
Slime spawns severly crippled / disabled completley

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/ATM-2#14]
Making report here from old tracker:
https://github.com/whatthedrunk/allthemods/issues/468

TL;DR - Slimes are *almost* never spawning, even in optimal and forced spawn conditions

**Comment by OrdinatorStouff** [comment]
Since tinker's slimes do *not* drop slime pearls (reliquary) we can consider adding an alternate recipe to craft them for the time being until we figure out why green slimes (and maybe magma cubes too) aren't spawning

**Comment by DrDelius** [comment]
To make this worse, we used tinker's Slimey modifier to create a normal green slime, captured it in an AA spawner changer, and made a green slime spawner... they won't spawn from the spawner. There is something horribly wrong going on here.

**Comment by Boomflex** [comment]
Old issue.

Fixed in newer builds.
