### ISSUE TITLE
Enable Refined Storage Debug

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/ATM-2#20]
In newest release, Raoul has created a debug log config option. When server updates please enable this config (at least for ATM2 server, but possibly as a default "client" config for ATM2 release). Details here: https://github.com/raoulvdberge/refinedstorage/issues/986#issuecomment-303466673

@raoulvdberge will this config option potentially cause performance issues? Would it hurt anything if we shipped the next version or two of ATM2 pack with it on by default in pack configs?

**Comment by raoulvdberge** [comment]
Shouldn't have any perf issues normally.

**Comment by OrdinatorStouff** [comment]
Then per raoul's input, @whatthedrunk I suggest we ship the pack with it on so even if SSP or other servers have the issue they'll already have the relevant log (and more data to hopefully track down the problem).

**Comment by whatthedrunk** [comment]
Changed for v0.68 which will be out soon.
