### ISSUE TITLE
atomic disassembler with vein mode and fluxed wire 

### ISSUE THREAD

**Issue by syrun97** [AllTheMods/ATM-2#22]
how to:
1. set your A.Disassembler as vein mode
2. break fluxed wire of fluxed redstone mod
3. CtD
[crash-2017-05-28_20.36.09-server.txt](https://github.com/AllTheMods/ATM-2/files/1034129/crash-2017-05-28_20.36.09-server.txt)

**Comment by Boomflex** [comment]
Old issue.

Fixed in newer builds.
