### ISSUE TITLE
Cows And Cursed Earth

### ISSUE THREAD

**Issue by SlubmeringSinh** [AllTheMods/ATM-2#24]
Apparently Animania bulls can spawn on cursed earth. Skeletons are capable of riding them so they spawn, but I have seen 2 clog my trap without a skeleton rider. No idea why it happens but its annoying.

**Comment by OrdinatorStouff** [comment]
Not only is it a possible annoyance but also a potential cause to crash the server: https://pastebin.com/YRnBzecz

Some combination of Animania, ExU2 Cursed Earth and Mob Totems results in a crash. Likely the main issue is that Animania bulls are some type of "hostile" mob so they show up in the cursed earth spawn table. The fact that they can have skele riders too makes me think they're perhaps an implementation of the spider AI that are passive (in daylight) until provoked.

**Comment by Tschipp** [comment]
Animania dev here. I'm guessing the skeleton dies and the bull remains. We are adding a config option to disable vanilla mobs riding animania ones

**Comment by OrdinatorStouff** [comment]
Interesting. So is the theory that it's the vanilla "feature" that a skeleton has a chance to spawn in riding an entity, and that Animania bulls are being considered as a potential mount?

**Comment by capnkirok** [comment]
Yes, exactly. But we add it manually anytime a skeleton spawns. You can turn this off in the latest version 1.1.3 in the config.

**Comment by capnkirok** [comment]
![image](https://user-images.githubusercontent.com/9628379/26898816-7c885576-4bcd-11e7-8e1d-742317f595de.png)

Conflict is between MobTotems and ExtraUtils
