### ISSUE TITLE
Mekanism Lithium Production

### ISSUE THREAD

**Issue by Bakamon0** [AllTheMods/ATM-2#27]
I currently don't see a recipe for Lithium.  The standard with it is to use Brine in a Thermal Evaporator to yield liquid Lithium.  This process is not taking completing while the components are in place.

[http://i.imgur.com/GQV4H2X.png](url)

**Comment by OrdinatorStouff** [comment]
Looks like this was a [known issue](https://github.com/aidancbrady/Mekanism/issues/4406) and has already been fixed in the code just need to get it downstream in a release and pack update (I am unable to determine if the release .306 has this fix in it or not)
