### ISSUE TITLE
Cloud Furnace dupe

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/ATM-2#28]
Cloud furnace might be able to dupe items. If confirmed AND if dev does not have update/fix soon then consider removing crafting recipe as temporary solution

https://github.com/ShetiPhian/Localizations-and-Issues/issues/82

**Comment by OrdinatorStouff** [comment]
Mod dev has fixed it and provided a compiled build with the fix:
http://www.mediafire.com/file/6e652laq2mwtwaw/terraqueous-1.11.0-1.3.14-RB1.jar

We just need to make sure the next pack update has a version that has the fix in

**Comment by Boomflex** [comment]
Updated to latest version as stated above.
