### ISSUE TITLE
Animania Leghorn Hens feather drop bug

### ISSUE THREAD

**Issue by Bookrage001** [AllTheMods/ATM-2#33]
Please Disable the following config due to chickens dropping way to many feathers.
animania.cfg
344        # Allow Animania Chickens to drop Feathers
345        B:chickensDropFeathers=true
as seen here: https://github.com/capnkirok/animania/issues/226

**Comment by ozhound** [comment]
Animalia has been removed entirely

**Comment by Bookrage001** [comment]
Well according to the change log it was just updated. so is this happening in the next update ?
(i also see it in game but haven't checked the mods folder)

**Comment by Bookrage001** [comment]
Waiting on pull request.

**Comment by ozhound** [comment]
it looks like we kept it in and changed the configs so that spawning wasn't
as prolific

**Comment by Boomflex** [comment]
I believe that config isnt to do with them passively dropping them. That is as a killed mob drop. The mod that makes the chickens drop feathers is Quark.

I have edited the Quark config.

**Comment by Bookrage001** [comment]
Still an issue version0.72a
