### ISSUE TITLE
Allthemods 2 V0.71 server got really lagie

### ISSUE THREAD

**Issue by Minebuddy** [AllTheMods/ATM-2#34]
after i did the update to the new version of Allthemods 2 V0.71 mobs where doing weird items did not pick up right away it did take 2 or 3 Seconds 

the server it self was also really lagie that was also why mobs and item pickup was doing weird

and as far as i can see console was not spamming error out

**Comment by Boomflex** [comment]
This is caused by a bug with TickDynamic, please remove this mod for now.

The new update v0.72a which will come out 21/06/17 will address this.
