### ISSUE TITLE
Ore Excavation does not work

### ISSUE THREAD

**Issue by Gorden211** [AllTheMods/ATM-2#35]
I tried version 0.72.  
I tried Tinker's Pickaxes, Vanilla Pickaxes (all of them) and none of them work. 
I checked the configs and nothing seems changed except for the logs and leaves being blocked (which is nice). 
But aside of that I could not get Ore Excavation to work with any configuration. With always on, with sneaking, with different buttons, with toggle on, with holding on. Nothing works.

**Comment by OrdinatorStouff** [comment]
@BloodWorkXGaming [created a mod ](https://minecraft.curseforge.com/projects/oreexcavation-integration)that makes Ore Excavator require either a tinker's modifier (craftable) or a tool enchant (rarely found form normal enchanting table) to work.

We should really look into finding some intuitive but unobstructive way to notify the player that they need the modifier/enchant. This could end up causing unnecessary reports to the Ore Excavator dev too...

**Comment by Gorden211** [comment]
Well thanks!
I missed that completely. Sorry for the inconvenience.  
I hope you and BloodWorkXGaming don't get more unnecessary reports because of this.
