### ISSUE TITLE
Suggestion Vanilla Chest from Quark Chest

### ISSUE THREAD

**Issue by Gorden211** [AllTheMods/ATM-2#37]
Not all mods using chests in recipes include oredictionary for chests (if that's a thing).  
For example the ExUtils transfer node can only be made with oak chests.
Instead of changing all the recipes that might be missing could you add a recipe that makes a vanilla oak chest from all the variants of quark chests so you don't have to specifically find oak wood for chests?

**Comment by Boomflex** [comment]
Hi Gorden211,

I have added the below script in the next version of the pack which adds exactly that :)

Any chest to oak chest (since it conflicts)
recipes.addShapeless(<minecraft:chest> * 1, [<quark:custom_chest:*>]);
