### ISSUE TITLE
Game crashes when i place 8 glass blocks in a rs crafting terminal to make a tank (idk if it does in other crafting methods)

### ISSUE THREAD

**Issue by cezieu** [AllTheMods/ATM-2#39]
Crash says it is a rendering issue. Tank appears correctly in crafting output and then my client crashes.
Here are 2 probably identical crash logs from this issue.
[crash-2017-06-27_17.10.15-client.txt](https://github.com/AllTheMods/ATM-2/files/1105773/crash-2017-06-27_17.10.15-client.txt)
[crash-2017-06-27_16.56.34-client.txt](https://github.com/AllTheMods/ATM-2/files/1105772/crash-2017-06-27_16.56.34-client.txt)

dentical crash logs from this issue.

**Comment by Boomflex** [comment]
Old issue.

Fixed in newer builds.
