### ISSUE TITLE
Mods Need To Be Updated

### ISSUE THREAD

**Issue by CluelessPhil** [AllTheMods/ATM-2#40]
Ok, how do i start this? CofhCore is crashing my server with the most recent version of SpongeForge and i'm sure you need to update CofhCore to its newest version so this issue can be fixed.

**Comment by ghost** [comment]
EletricBlue1, The CofhCore is fixed in the latest version of spongeforge 1.11 as I just tested it the other day and it worked

**Comment by Boomflex** [comment]
SpongeForge is not supported by us.
