### ISSUE TITLE
recipe issue with "diamondchip"(from open computers)

### ISSUE THREAD

**Issue by neo130288** [AllTheMods/ATM-2#41]
you are unable to craft this item meaning most of the "good" stuff in open computer's is unusable 

i try my self to edit my server config for open computers recipes but it seams to be overwriting the file on load and shutdown of a server and it just reverts back to default.

**Comment by neo130288** [comment]
ok so after having a bit of sleep i found a work around that keep the orignal "price" for the chips of 1 diamond into 6 diamond chips

the following to be placed in here   All the Mods 2\scripts\edited_recipes.zs
// Make Diamond Chips craftable using diamond nuggets instead of full diamonds, conflicting recipe fix.
val diamondChip = <opencomputers:material:29>;
val diamondNugget = <ore:nuggetDiamond>;

recipes.remove(diamondChip);

recipes.addShapeless(diamondChip * 2, [diamondNugget, diamondNugget, diamondNugget]);

**Comment by Boomflex** [comment]
Old issue.

Fixed in newer builds.
