### ISSUE TITLE
Weird Chest/Sign Render Bug - Invisible chests

### ISSUE THREAD

**Issue by MokahTGS** [AllTheMods/ATM-2#42]
We are getting an odd issue with chests not rendering until you look at them or open them.  We are also having signs that are attached to the chests loose their text.  This happens to some chests/signs and not all.

**Comment by Gorden211** [comment]
Also Colossal Chests have a broken purple/black texture, all except for the wooden one.

**Comment by Boomflex** [comment]
Updated with v0.74
