### ISSUE TITLE
The Chickens shed feathers very fast

### ISSUE THREAD

**Issue by tattila8** [AllTheMods/ATM-2#44]
I have problem with chickens, they shed feathers very fast, how can i solve this problem?

**Comment by JustaRandom** [comment]
If you go in your folder /config and look into animania.cfg 
There is a value which is 
         # Ticks between dropping feathers
        I:featherTimer=12000
(this is the default) you might have to bump that to an higher value which would solve your problem.

peace

**Comment by Boomflex** [comment]
Old issue.

Fixed in newer builds.
