### ISSUE TITLE
0.73 Twitch issues?

### ISSUE THREAD

**Issue by JustaRandom** [AllTheMods/ATM-2#48]
I do not know if this is an issue with the twitch app client but when updating for previous version I believe the 0.72d (the latest old one) there are some duplicate files which sneaks in.

I do have 31 files which where duplicated and caused a crash on startup of the game. After removal of said files the game is launching fine.

If someone has the same problem just go to the mod folders and check for duplicate of the same mod.

Peace Gildd

**Comment by Boomflex** [comment]
Old issue.

Fixed in newer builds.
