### ISSUE TITLE
Recipe conflict: name tag / golden lasso

### ISSUE THREAD

**Issue by Ricket** [AllTheMods/ATM-2#50]
Golden lasso has the same recipe as name tag (well, plus xp). Doesn't seem there is a way to craft the golden lasso.

ATM2 v0.73

(seems like maybe this would be mitigated if NoMoreRecipeConflict was in the pack?)

**Comment by Jkiller175** [comment]
Having the same issue, however i discovered that the old recipe (4 gold nuggets in the corners + 4 string on sides) still works, not that jei reflects this. Obviously this conflict needs to be resolved, but i figure this is a decent workaround until said resolve happens.

**Comment by meelock** [comment]
Yep same, please fix this all the mods team!

**Comment by Sabster** [comment]
There is - use the default recipe:  string in 4 corners - gold nugget in the N, E, W, S positions (nothing in the middle)

**Comment by Boomflex** [comment]
Fixed in v0.74.
