### ISSUE TITLE
Block weirdness on rftools dimension

### ISSUE THREAD

**Issue by gmunaro** [AllTheMods/ATM-2#6]
Looks like that machines are having issues when trying to place or destroy a block from the world when inside a rftools dimension. 

Blocks like the Autobreaker (AA) or Destructor(RefStorage) doesnt work, and the breaker block from Embers only whorks when your cross hair is in them(?lol?) So, i think that the real problem is somekind of config related to the FTB permissions, or something like it. Help?  (Aobozu here)

**Comment by gmunaro** [comment]
TEMPORARY FIX> walk 1k blocks, and everything will work

**Comment by Boomflex** [comment]
Old issue.

Fixed in newer builds.
