### ISSUE TITLE
Refined Storage Solderer Output Problem

### ISSUE THREAD

**Issue by Bakamon0** [AllTheMods/ATM-2#7]
Using a gold block in solderer outputs "Printed Basic Processor" while it should be "Printed Improved Processor" [http://i.imgur.com/TooQrLy.png](url)

**Comment by OrdinatorStouff** [comment]
submitted ticket to RS dev tracker: https://github.com/raoulvdberge/refinedstorage/issues/1231

**Comment by OrdinatorStouff** [comment]
Per input form Raoul, we need to modify ore dictionary entries on the items themselves. This could possibly be from UniDict or maybe another mod, needs further investigation to track down.

The offending oredict registry is "blockMetal"

A minetweaker script can remove the iron and gold blocks from that registry as a simple fix or we can find what mod is adding the entire registration and see if it's needed for anything

**Comment by OrdinatorStouff** [comment]
It's possible that [TiCo](https://github.com/SlimeKnights/TinkersConstruct/blob/1.11.2/src/main/java/slimeknights/tconstruct/common/TinkerOredict.java#L162) seems to be the mod adding "blockMetal"

**Comment by Boomflex** [comment]
Old issue.

Fixed in newer builds.
