### ISSUE TITLE
Deep Dark

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/ATM-2#8]
Known issue, posting here for visibility / in case anyone else comes along.

Deep Dark in ATM2 causes severe lag. If on a server, it lags the entire server (20 TPS to 2 TPS) just from being inside the dimensions. Not worldgen related since you can idle there for hours and it'll still be just as laggy.

Unless fixed in a recent update consider disabling the deep dark or disable the portal's crafting recipe.

Example report on ExU2 tracker: https://github.com/rwtema/extrautilities/issues/1007

**Comment by whatthedrunk** [comment]
Deep Dark is Disabled as of v0.67 feel free to let me know if it gets fixed and I will enable it again.

**Comment by OrdinatorStouff** [comment]
Deep dark PORTAL is still craftable and if crafted and used the entire server will crash.

Recommend removing deep dark portal with crafttweaker and adding "The Beneath" instead. (Or just disable deep dark portal crafting recipe at least).

**Comment by OrdinatorStouff** [comment]
As of latest update the ATM2 server is still crashing due to people attempting to visit the deep dark.

**Comment by whatthedrunk** [comment]
Removed in the next update that will be out in 1-30 hours :P
